global:
  evaluation_interval: 15s
  scrape_interval: 15s

rule_files:
  - rules.yml

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:
  - job_name: adapters
    static_configs:
      - labels:
          namespace: adapters
        targets:
          - coingecko-adapter:9080
          - coinmarketcap-adapter:9080
          - tiingo-adapter:9080

